// Code generated by protoc-gen-go. DO NOT EDIT.
// source: wallet.proto

package grpc

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Wallet struct {
	WalletId             []byte                 `protobuf:"bytes,1,opt,name=wallet_id,json=walletId,proto3" json:"wallet_id,omitempty"`
	Owner                string                 `protobuf:"bytes,2,opt,name=owner,proto3" json:"owner,omitempty"`
	Balance              int64                  `protobuf:"varint,3,opt,name=balance,proto3" json:"balance,omitempty"`
	Currency             string                 `protobuf:"bytes,4,opt,name=currency,proto3" json:"currency,omitempty"`
	CreatedAt            *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt            *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *Wallet) Reset()         { *m = Wallet{} }
func (m *Wallet) String() string { return proto.CompactTextString(m) }
func (*Wallet) ProtoMessage()    {}
func (*Wallet) Descriptor() ([]byte, []int) {
	return fileDescriptor_b88fd140af4deb6f, []int{0}
}

func (m *Wallet) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Wallet.Unmarshal(m, b)
}
func (m *Wallet) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Wallet.Marshal(b, m, deterministic)
}
func (m *Wallet) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Wallet.Merge(m, src)
}
func (m *Wallet) XXX_Size() int {
	return xxx_messageInfo_Wallet.Size(m)
}
func (m *Wallet) XXX_DiscardUnknown() {
	xxx_messageInfo_Wallet.DiscardUnknown(m)
}

var xxx_messageInfo_Wallet proto.InternalMessageInfo

func (m *Wallet) GetWalletId() []byte {
	if m != nil {
		return m.WalletId
	}
	return nil
}

func (m *Wallet) GetOwner() string {
	if m != nil {
		return m.Owner
	}
	return ""
}

func (m *Wallet) GetBalance() int64 {
	if m != nil {
		return m.Balance
	}
	return 0
}

func (m *Wallet) GetCurrency() string {
	if m != nil {
		return m.Currency
	}
	return ""
}

func (m *Wallet) GetCreatedAt() *timestamppb.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func (m *Wallet) GetUpdatedAt() *timestamppb.Timestamp {
	if m != nil {
		return m.UpdatedAt
	}
	return nil
}

type CreateWalletRequest struct {
	Owner                string   `protobuf:"bytes,1,opt,name=owner,proto3" json:"owner,omitempty"`
	Balance              int64    `protobuf:"varint,2,opt,name=balance,proto3" json:"balance,omitempty"`
	Currency             string   `protobuf:"bytes,3,opt,name=currency,proto3" json:"currency,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateWalletRequest) Reset()         { *m = CreateWalletRequest{} }
func (m *CreateWalletRequest) String() string { return proto.CompactTextString(m) }
func (*CreateWalletRequest) ProtoMessage()    {}
func (*CreateWalletRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b88fd140af4deb6f, []int{1}
}

func (m *CreateWalletRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateWalletRequest.Unmarshal(m, b)
}
func (m *CreateWalletRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateWalletRequest.Marshal(b, m, deterministic)
}
func (m *CreateWalletRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateWalletRequest.Merge(m, src)
}
func (m *CreateWalletRequest) XXX_Size() int {
	return xxx_messageInfo_CreateWalletRequest.Size(m)
}
func (m *CreateWalletRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateWalletRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateWalletRequest proto.InternalMessageInfo

func (m *CreateWalletRequest) GetOwner() string {
	if m != nil {
		return m.Owner
	}
	return ""
}

func (m *CreateWalletRequest) GetBalance() int64 {
	if m != nil {
		return m.Balance
	}
	return 0
}

func (m *CreateWalletRequest) GetCurrency() string {
	if m != nil {
		return m.Currency
	}
	return ""
}

type CreateWalletResponse struct {
	Wallet               *Wallet  `protobuf:"bytes,1,opt,name=wallet,proto3" json:"wallet,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateWalletResponse) Reset()         { *m = CreateWalletResponse{} }
func (m *CreateWalletResponse) String() string { return proto.CompactTextString(m) }
func (*CreateWalletResponse) ProtoMessage()    {}
func (*CreateWalletResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b88fd140af4deb6f, []int{2}
}

func (m *CreateWalletResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateWalletResponse.Unmarshal(m, b)
}
func (m *CreateWalletResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateWalletResponse.Marshal(b, m, deterministic)
}
func (m *CreateWalletResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateWalletResponse.Merge(m, src)
}
func (m *CreateWalletResponse) XXX_Size() int {
	return xxx_messageInfo_CreateWalletResponse.Size(m)
}
func (m *CreateWalletResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateWalletResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateWalletResponse proto.InternalMessageInfo

func (m *CreateWalletResponse) GetWallet() *Wallet {
	if m != nil {
		return m.Wallet
	}
	return nil
}

func init() {
	proto.RegisterType((*Wallet)(nil), "pb.Wallet")
	proto.RegisterType((*CreateWalletRequest)(nil), "pb.CreateWalletRequest")
	proto.RegisterType((*CreateWalletResponse)(nil), "pb.CreateWalletResponse")
}

func init() {
	proto.RegisterFile("wallet.proto", fileDescriptor_b88fd140af4deb6f)
}

var fileDescriptor_b88fd140af4deb6f = []byte{
	// 310 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x91, 0xb1, 0x4e, 0xf3, 0x30,
	0x14, 0x85, 0xe5, 0xf6, 0x6f, 0xfe, 0xd6, 0xed, 0x64, 0x3a, 0x44, 0x65, 0x20, 0xca, 0x94, 0x05,
	0x47, 0xb4, 0x13, 0x6c, 0xa5, 0x62, 0x60, 0x8d, 0x90, 0x90, 0x58, 0x2a, 0xc7, 0xb9, 0x04, 0x4b,
	0x49, 0x6c, 0x9c, 0x1b, 0x2a, 0x78, 0x61, 0x5e, 0x03, 0x61, 0x27, 0xa0, 0x0e, 0x15, 0x5b, 0xce,
	0xcd, 0x39, 0xbe, 0xe7, 0xb3, 0xe9, 0xe2, 0x20, 0xaa, 0x0a, 0x90, 0x1b, 0xab, 0x51, 0xb3, 0x91,
	0xc9, 0x57, 0x17, 0xa5, 0xd6, 0x65, 0x05, 0xa9, 0x9b, 0xe4, 0xdd, 0x73, 0x8a, 0xaa, 0x86, 0x16,
	0x45, 0x6d, 0xbc, 0x29, 0xfe, 0x24, 0x34, 0x78, 0x74, 0x29, 0x76, 0x4e, 0x67, 0x3e, 0xbf, 0x57,
	0x45, 0x48, 0x22, 0x92, 0x2c, 0xb2, 0xa9, 0x1f, 0xdc, 0x17, 0x6c, 0x49, 0x27, 0xfa, 0xd0, 0x80,
	0x0d, 0x47, 0x11, 0x49, 0x66, 0x99, 0x17, 0x2c, 0xa4, 0xff, 0x73, 0x51, 0x89, 0x46, 0x42, 0x38,
	0x8e, 0x48, 0x32, 0xce, 0x06, 0xc9, 0x56, 0x74, 0x2a, 0x3b, 0x6b, 0xa1, 0x91, 0xef, 0xe1, 0x3f,
	0x17, 0xf9, 0xd1, 0xec, 0x9a, 0x52, 0x69, 0x41, 0x20, 0x14, 0x7b, 0x81, 0xe1, 0x24, 0x22, 0xc9,
	0x7c, 0xbd, 0xe2, 0xbe, 0x29, 0x1f, 0x9a, 0xf2, 0x87, 0xa1, 0x69, 0x36, 0xeb, 0xdd, 0x5b, 0xfc,
	0x8e, 0x76, 0xa6, 0x18, 0xa2, 0xc1, 0xdf, 0xd1, 0xde, 0xbd, 0xc5, 0x58, 0xd0, 0xb3, 0x9d, 0x3b,
	0xc7, 0xe3, 0x66, 0xf0, 0xda, 0x41, 0x8b, 0xbf, 0x60, 0xe4, 0x04, 0xd8, 0xe8, 0x34, 0xd8, 0xf8,
	0x18, 0x2c, 0xbe, 0xa1, 0xcb, 0xe3, 0x15, 0xad, 0xd1, 0x4d, 0x0b, 0x2c, 0xa6, 0x81, 0xbf, 0x48,
	0xb7, 0x64, 0xbe, 0xa6, 0xdc, 0xe4, 0xbc, 0xf7, 0xf4, 0x7f, 0x6e, 0xef, 0x9e, 0x76, 0xa5, 0xc2,
	0x97, 0x2e, 0xe7, 0x52, 0xd7, 0xa9, 0x85, 0x0f, 0xb1, 0xad, 0x95, 0x55, 0x57, 0xeb, 0x4d, 0x8a,
	0xd0, 0xe2, 0x65, 0xad, 0xa4, 0xd5, 0x2d, 0xd8, 0x37, 0x25, 0x21, 0xed, 0xdf, 0x69, 0x90, 0x0e,
	0x3c, 0x2d, 0xad, 0x91, 0x79, 0xe0, 0xbe, 0x37, 0x5f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x94, 0x0d,
	0x2d, 0xc9, 0x0b, 0x02, 0x00, 0x00,
}
