definitions:
  article.Article:
    properties:
      body:
        type: string
      description:
        type: string
      slug:
        type: string
      title:
        type: string
      user_uuid:
        type: string
      uuid:
        type: string
    required:
    - body
    - title
    type: object
  dto.CreateArticleRequest:
    properties:
      body:
        type: string
      description:
        type: string
      title:
        type: string
    required:
    - body
    - title
    type: object
  dto.CreateArticleResponse:
    properties:
      article:
        $ref: '#/definitions/article.Article'
        type: object
    type: object
info:
  contact: {}
  license: {}
paths:
  /articles/create:
    post:
      consumes:
      - application/json
      description: Create article handler
      parameters:
      - description: Authorization
        in: header
        name: Authorization
        required: true
        type: string
      - description: New Article
        in: body
        name: article
        required: true
        schema:
          $ref: '#/definitions/dto.CreateArticleRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/dto.CreateArticleResponse'
      security:
      - ApiKeyAuth: []
      summary: Create article
      tags:
      - Articles
swagger: "2.0"
